Cube results table scrolls with videos
NextCenturyCorporation/mcs-ui pull request #94
Opened 2022-06-08 21:39 UTC by jaudick

The table now scrolls with a fixed header. The position of the highlighted current scene will always be in view of the table window. This is helpful especially for the play all feature as the table scrolls with the videos as you play through each scene moving down the table.

2022-06-13 13:39 UTC, ThomasSchellenbergNextCentury approved these changes
I haven't tested it myself, but the code looks fine to me.

2022-06-13 17:38 UTC, brianpippin requested changes
This only brings the scene into view from the bottom part of the scroll, I think we want the highlighted one when playing all to be at the top of the scroll panel, not at the bottom.  It can be too hard to find sometimes at the bottom.  I also think it might do the table some justice to shrink the size of the fixed height as well.

2022-06-22 13:44 UTC, brianpippin commented on analysis-ui/src/components/Analysis/scenes.jsx
> +                    sceneRow.style.position = 'relative';
Is there anyway we can clean up this function by using classes and react rerenders?

2022-06-22 13:44 UTC, brianpippin commented
Love the functionality and how it is working now, that one function just seems like it could be a little more react like.

2022-06-23 21:34 UTC, jaudick commented on analysis-ui/src/components/Analysis/scenes.jsx
> +                    sceneRow.style.position = 'relative';
I pushed a commit that changes these to classes. All of my attempts at putting it in a react rerender made me lose the functionality of being able to click a row and not have the table scroll on the click. I feel like we want to keep it so clicking **does not** scroll that row to the top, but clicking the up or down one scene buttons or play all **does** scroll so I think this class change is the most optimized it can be.

2022-06-24 19:48 UTC, merged